install:
  # texlive
  - sudo apt-get install -qq texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended 
  # ocaml](http://ocaml.org/)
  - sudo apt-get install -qq ocaml
  # hevea
  - sudo apt-get install -qq hevea
  # imagemagick
  - sudo apt-get install -qq imagemagick
  # Flask
  - sudo apt-get install -qq flask
  # Calibre, for ebook-convert
  - sudo apt-get install -qq calibre
  # epubcheck
  - sudo apt-get install -qq epubcheck

script:
  - wget https://raw.githubusercontent.com/richelbilderbeek/travis_pandoc_tex_to_epub/master/example.tex
  - python tex2ebook.py example.tex
  - epubcheck example.epub