install:
  - sudo apt-get install -qq texlive-latex-recommended texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended ocaml hevea imagemagick python2.7 python-flask calibre epubcheck

script:
  - wget https://raw.githubusercontent.com/richelbilderbeek/travis_pandoc_tex_to_epub/master/example.tex
  - cat example.tex
  - python tex2ebook.py example.tex -o example.epub
  - cat example.epub
  - epubcheck example.epub